version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18 # Or a different compatible Node.js version
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build # This runs the vite build command
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  baseDirectory: dist # The output directory for Vite
