version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  install:
    commands:
      - npm install --include=dev

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
